# dockerfile.dev
# This Dockerfile is for local development.
# It uses the pre-built base image which contains all dependencies.

FROM autogen-chatbot-base-dev

# Set the working directory inside the container.
WORKDIR /app

CMD ["uvicorn", "main_server:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]