
services:
  dev:
    build:
      context: . # current directory as the build context.
      dockerfile: Dockerfile.dev # development Dockerfile.

    # Mounts local project directory ('.') into the container's /app directory.
    volumes:
      - .:/app
      
    # Maps port 8000 on your local machine to port 8000 in the container.
    ports:
      - "8000:8000"
    # Ensure logs appear in real-time.
    environment:
      - PYTHONUNBUFFERED=1