# /src/markdown_info/quick_replies/live_product_references.py
from .quick_reply_markdown import (
    QUICK_REPLIES_START_TAG,
    QUICK_REPLIES_END_TAG,
)

# Contains example "Quick Replies: [...]" string constants for the Live Product Agent (LPA)
# to use in its system message examples or for internal reference.

# Example for product clarification when multiple products match
LPA_PRODUCT_CLARIFICATION_QR = f'{QUICK_REPLIES_START_TAG}<product_clarification>:["Removable Vinyl Stickers (Pages, Glossy)", "Clear Static Cling (Kiss-cut singles)", "None of these / Need more help"]{QUICK_REPLIES_END_TAG}'

# Example for listing countries (a small subset for the example)
LPA_COUNTRY_SELECTION_QR = f'{QUICK_REPLIES_START_TAG}<country_selection>:["United States", "Canada", "United Kingdom"]{QUICK_REPLIES_END_TAG}'

# Example for confirming if the product identified by the agent is correct.
LPA_PRODUCT_CONFIRMATION_QR = f'{QUICK_REPLIES_START_TAG}<product_confirmation>:["Yes, that\'s the one!|yes_correct_product", "No, that\'s not it|no_incorrect_product"]{QUICK_REPLIES_END_TAG}'

# Products with quick reply labels
LPA_PRODUCT_QUICK_REPLIES_LABELS = [
    {
        "productId": 1,
        "name": "Removable Vinyl Stickers",
        "format": "Pages",
        "material": "Removable White Vinyl (Glossy)",
        "quick_reply_label": "Removable Vinyl Stickers (Pages, Glossy)",
    },
    {
        "productId": 2,
        "name": "Removable Clear Stickers",
        "format": "Pages",
        "material": "Removable Clear Vinyl",
        "quick_reply_label": "Removable Clear Stickers (Pages, Removable clear vinyl)",
    },
    {
        "productId": 3,
        "name": "Removable Vinyl Labels",
        "format": "Pages",
        "material": "Removable White Vinyl (Glossy)",
        "quick_reply_label": "Removable White Vinyl Labels (Pages, Glossy)",
    },
    {
        "productId": 4,
        "name": "Removable Clear Labels",
        "format": "Pages",
        "material": "Removable Clear Vinyl",
        "quick_reply_label": "Removable Clear Labels (Pages, Clear Vinyl)",
    },
    {
        "productId": 5,
        "name": "Iron-Ons",
        "format": "Pages",
        "material": "Iron-On",
        "quick_reply_label": "Iron-Ons (Pages)",
    },
    {
        "productId": 6,
        "name": "Temporary Tattoos",
        "format": "Pages",
        "material": "Temporary Tattoo",
        "quick_reply_label": "Temporary Tattoos (Pages)",
    },
    {
        "productId": 7,
        "name": "Permanent Vinyl Stickers",
        "format": "Pages",
        "material": "Permanent White Vinyl",
        "quick_reply_label": "Permanent Vinyl Stickers (Pages, White vinyl)",
    },
    {
        "productId": 8,
        "name": "Stick-On Clothing Labels",
        "format": "Pages",
        "material": "Permanent White Vinyl",
        "quick_reply_label": "Stick-On Clothing Labels (Pages, Permanent white vinyl)",
    },
    {
        "productId": 10,
        "name": "Default Product",
        "format": "Pages",
        "material": "Clear Static Cling",
        "quick_reply_label": "Clear Static Cling (Pages)",
    },
    {
        "productId": 11,
        "name": "Removable Vinyl Sticker Hand-Outs",
        "format": "Kiss-cut Singles",
        "material": "Removable White Vinyl (Glossy)",
        "quick_reply_label": "Removable White Vinyl Sticker Hand-Outs (Kiss-cut singles, Glossy)",
    },
    {
        "productId": 12,
        "name": "Removable Clear Sticker Hand-Outs",
        "format": "Kiss-cut Singles",
        "material": "Removable Clear Vinyl",
        "quick_reply_label": "Removable Clear Sticker Hand-Outs (Kiss-cut singles, Clear vinyl)",
    },
    {
        "productId": 13,
        "name": "Temporary Tattoo Hand-Outs",
        "format": "Kiss-cut Singles",
        "material": "Temporary Tattoo",
        "quick_reply_label": "Temporary Tattoo Hand-Outs (Kiss-cut singles)",
    },
    {
        "productId": 14,
        "name": "Premium Kids Vinyl Labels",
        "format": "Kids Labels",
        "material": "Removable White Vinyl (Glossy)",
        "quick_reply_label": "Premium Kids Vinyl Labels (Kids Labels, White vinyl, Glossy)",
    },
    {
        "productId": 15,
        "name": "Roll Labels - White Permanent Paper",
        "format": "Rolls",
        "material": "White Permanent Roll Paper",
        "quick_reply_label": "Roll Labels (Roll, White permanent paper)",
    },
    {
        "productId": 16,
        "name": "Clear Roll Label",
        "format": "Rolls",
        "material": "Permanent Clear Polypropylene",
        "quick_reply_label": "Clear Roll Label (Roll, Permanent clear polypropylene)",
    },
    {
        "productId": 17,
        "name": "Indoor Wall Decal Smooth",
        "format": "Custom Decals",
        "material": "Wall Decal",
        "quick_reply_label": "Indoor Wall Decal Smooth (Custom Decals)",
    },
    {
        "productId": 19,
        "name": "Slip Resistant Decal",
        "format": "Custom Decals",
        "material": "Wall and Walk",
        "quick_reply_label": "Slip Resistant Decal (Custom Decals, Wall and walk)",
    },
    {
        "productId": 23,
        "name": "Dry-Erase Cloud",
        "format": "Ready-made or specialty",
        "material": "",
        "quick_reply_label": "Dry-Erase Cloud (Ready-made or specialty)",
    },
    {
        "productId": 24,
        "name": "Chalk Decal Rectangle",
        "format": "Ready-made or specialty",
        "material": "",
        "quick_reply_label": "Chalk Decal Rectangle (Ready-made or specialty)",
    },
    {
        "productId": 25,
        "name": "Chalk Decal Fancy",
        "format": "Ready-made or specialty",
        "material": "",
        "quick_reply_label": "Chalk Decal Fancy (Ready-made or specialty)",
    },
    {
        "productId": 26,
        "name": "Map Decal USA",
        "format": "Ready-made or specialty",
        "material": "",
        "quick_reply_label": "Map Decal USA (Ready-made or specialty)",
    },
    {
        "productId": 27,
        "name": "Signature Wall Decal",
        "format": "Predesigned Decals",
        "material": "Wall Decal",
        "quick_reply_label": "Signature Wall Decal (Predesigned Decals)",
    },
    {
        "productId": 28,
        "name": "Vinyl Lettering",
        "format": "Vinyl Lettering",
        "material": "Removable White Vinyl (Glossy)",
        "quick_reply_label": "Vinyl Lettering (White vinyl, Glossy)",
    },
    {
        "productId": 29,
        "name": "Large Format Removable Clear Decal",
        "format": "Custom Decals",
        "material": "Removable Clear Vinyl",
        "quick_reply_label": "Large Format Removable Clear Decal (Custom Decals, Removable clear vinyl)",
    },
    {
        "productId": 30,
        "name": "Durable Roll Label",
        "format": "Rolls",
        "material": "Bopp",
        "quick_reply_label": "Durable Roll Label (Roll, Bopp)",
    },
    {
        "productId": 31,
        "name": "Clear Static Cling",
        "format": "Kiss-cut Singles",
        "material": "Clear Static Cling",
        "quick_reply_label": "Clear Static Cling (Kiss-cut singles)",
    },
    {
        "productId": 32,
        "name": "Removable Vinyl Stickers (Matte)",
        "format": "Pages",
        "material": "Removable White Vinyl (Matte)",
        "quick_reply_label": "Removable Vinyl Stickers (Pages, Matte)",
    },
    {
        "productId": 33,
        "name": "Removable Vinyl Labels (Matte)",
        "format": "Pages",
        "material": "Removable White Vinyl (Matte)",
        "quick_reply_label": "Removable Vinyl Labels (Pages, Matte)",
    },
    {
        "productId": 34,
        "name": "Decorative Decal",
        "format": "Custom Decals",
        "material": "Wall Decal",
        "quick_reply_label": "Decorative Wall Decal (Custom Decals)",
    },
    {
        "productId": 35,
        "name": "Clear Static Cling",
        "format": "Kiss-cut Singles",
        "material": "Clear Static Cling",
        "quick_reply_label": "Clear Static Cling (Kiss-cut singles)",
    },
    {
        "productId": 36,
        "name": "Canvas Patch",
        "format": "Die-cut Singles",
        "material": "Canvas",
        "quick_reply_label": "Canvas Patch (Die-cut Singles)",
    },
    {
        "productId": 37,
        "name": "Removable White Vinyl (Matte) Hand-Outs",
        "format": "Kiss-cut Singles",
        "material": "Removable White Vinyl (Matte)",
        "quick_reply_label": "Removable White Vinyl Hand-Outs (Kiss-cut singles, Matte)",
    },
    {
        "productId": 38,
        "name": "Removable White Vinyl (Semi-Glossy)",
        "format": "Die-cut Singles",
        "material": "Removable White Vinyl (Semi-Glossy)",
        "quick_reply_label": "Removable White Vinyl (Die-cut Singles, Semi-Glossy)",
    },
    {
        "productId": 39,
        "name": "Writable Matte Bopp Roll",
        "format": "Rolls",
        "material": "Writable Matte Bopp",
        "quick_reply_label": "Writable Matte Bopp (Roll)",
    },
    {
        "productId": 42,
        "name": "Silver Foil Roll Label",
        "format": "Rolls",
        "material": "Silver Foil Label",
        "quick_reply_label": "Silver Foil Roll Label (Roll)",
    },
    {
        "productId": 43,
        "name": "Name Badges",
        "format": "Die-cut Singles",
        "material": "Durable Plastic with Magnet",
        "quick_reply_label": "Name Badges (Die-cut Singles, Durable plastic with magnet)",
    },
    {
        "productId": 44,
        "name": "Magnet Singles",
        "format": "Die-cut Singles",
        "material": "Magnet",
        "quick_reply_label": "Magnet Singles (Die-cut Singles)",
    },
    {
        "productId": 45,
        "name": "Laminated Die-Cut Singles",
        "format": "Die-cut Singles",
        "material": "Laminated Removable White Vinyl (Matte)",
        "quick_reply_label": "Laminated Die-Cut Singles (Removable white vinyl, Matte)",
    },
    {
        "productId": 46,
        "name": "Gold Foil Roll Label",
        "format": "Rolls",
        "material": "Silver Foil Label",
        "quick_reply_label": "Gold Foil Roll Label (Roll, Foil)",
    },
    {
        "productId": 47,
        "name": "Iron-On Transfers No Background",
        "format": "Vinyl Lettering",
        "material": "Iron-On",
        "quick_reply_label": "Iron-On Transfers No Background (Vinyl Lettering)",
    },
    {
        "productId": 48,
        "name": "White Static Cling",
        "format": "Kiss-cut Singles",
        "material": "White Cling",
        "quick_reply_label": "White Static Cling (Kiss-cut singles)",
    },
    {
        "productId": 49,
        "name": "Removable White Paper",
        "format": "Rolls",
        "material": "Paper (glossy, removable)",
        "quick_reply_label": "Removable White Paper (Roll, Paper, glossy, removable)",
    },
    {
        "productId": 50,
        "name": "White Static Cling",
        "format": "Kiss-cut Singles",
        "material": "White Cling",
        "quick_reply_label": "White Static Cling (Kiss-cut singles)",
    },
    {
        "productId": 51,
        "name": "White Permanent Plain Paper Rolls",
        "format": "Rolls",
        "material": "Eco-Safe Paper (semi-gloss, permanent)",
        "quick_reply_label": "White Permanent Plain Paper Rolls (Eco-Safe paper, semi-gloss)",
    },
    {
        "productId": 52,
        "name": "Removable Holographic",
        "format": "Die-cut Singles",
        "material": "Removable Holographic",
        "quick_reply_label": "Removable Holographic (Die-cut Singles)",
    },
    {
        "productId": 53,
        "name": "Permanent Glitter",
        "format": "Die-cut Singles",
        "material": "Permanent Glitter",
        "quick_reply_label": "Permanent Glitter (Die-cut Singles)",
    },
    {
        "productId": 55,
        "name": "Clear Die-Cut Stickers",
        "format": "Die-cut Singles",
        "material": "Removable Clear Vinyl",
        "quick_reply_label": "Clear Die-Cut Stickers (Die-cut Singles, Removable clear vinyl)",
    },
    {
        "productId": 56,
        "name": "Car Magnet",
        "format": "Die-cut Singles",
        "material": "Car Magnet",
        "quick_reply_label": "Car Magnet (Die-cut Singles)",
    },
    {
        "productId": 57,
        "name": "Permanent Die-Cut Singles",
        "format": "Die-cut Singles",
        "material": "Permanent White Vinyl (Semi-Glossy)",
        "quick_reply_label": "Permanent Die-Cut Singles (Permanent white vinyl, Semi-Glossy)",
    },
    {
        "productId": 58,
        "name": "White Paper Pouch Label",
        "format": "Pouches",
        "material": "White Permanent Roll Paper",
        "quick_reply_label": "White Paper Pouch Label (Pouches, White permanent roll paper)",
    },
    {
        "productId": 59,
        "name": "Clear Pouch Label",
        "format": "Pouches",
        "material": "Permanent Clear Polypropylene",
        "quick_reply_label": "Clear Pouch Label (Pouches, Permanent clear polypropylene)",
    },
    {
        "productId": 60,
        "name": "Durable White Pouch Label",
        "format": "Pouches",
        "material": "Bopp",
        "quick_reply_label": "Durable White Pouch Label (Pouches, Bopp)",
    },
    {
        "productId": 61,
        "name": "Silver Foil Pouch Label",
        "format": "Pouches",
        "material": "Silver Foil Label",
        "quick_reply_label": "Silver Foil Pouch Label (Pouches)",
    },
    {
        "productId": 62,
        "name": "Gold Foil Pouch Label",
        "format": "Pouches",
        "material": "Silver Foil Label",
        "quick_reply_label": "Gold Foil Pouch Label (Pouches, Silver foil)",
    },
    {
        "productId": 63,
        "name": "Eco-Safe Pouch Label",
        "format": "Pouches",
        "material": "Eco-Safe Paper (semi-gloss, permanent)",
        "quick_reply_label": "Eco-Safe Paper Pouch Label (Pouches, semi-gloss, permanent)",
    },
    {
        "productId": 64,
        "name": "Yard Sign",
        "format": "Yard Sign",
        "material": "White Corrugated Board",
        "quick_reply_label": "Yard Sign (White corrugated board)",
    },
    {
        "productId": 65,
        "name": "Shiny Colored Foil",
        "format": "Rolls",
        "material": "Silver Foil Label",
        "quick_reply_label": "Shiny Colored Foil (Roll, Silver foil label)",
    },
    {
        "productId": 66,
        "name": "Eco-Safe Stickers",
        "format": "Die-cut Singles",
        "material": "Removable Eco-Safe PET (Matte)",
        "quick_reply_label": "Eco-Safe Stickers (Die-cut Singles, Removable eco-safe pet, Matte)",
    },
    {
        "productId": 67,
        "name": "Mini Pages",
        "format": "Kiss-cut Mini Pages",
        "material": "Removable White Vinyl (Glossy)",
        "quick_reply_label": "Mini Pages (Kiss-cut Mini Pages, Removable white vinyl, Glossy)",
    },
    {
        "productId": 68,
        "name": "Image Transfers",
        "format": "Image Transfers",
        "material": "Permanent Image Transfer (Glossy)",
        "quick_reply_label": "Image Transfers (Permanent image transfer, Glossy)",
    },
    {
        "productId": 69,
        "name": "Smart Save Removable Die-Cut Singles",
        "format": "Die-cut Singles",
        "material": "Removable Smart Save",
        "quick_reply_label": "Removable Smart Save Die-Cut Singles",
    },
    {
        "productId": 70,
        "name": "Image Transfer Iron-Ons (DTF)",
        "format": "DTF Transfers",
        "material": "PET Film",
        "quick_reply_label": "Image Transfer Iron-Ons (DTF Transfers, PET film)",
    },
    {
        "productId": 71,
        "name": "Optically Clear Vinyl",
        "format": "Kiss-cut Singles",
        "material": "Removable Optically Clear Vinyl",
        "quick_reply_label": "Optically Clear Vinyl (Kiss-cut singles)",
    },
    {
        "productId": 72,
        "name": "Removable Smart Save Stickers",
        "format": "Kiss-cut Mini Pages",
        "material": "Removable Smart Save",
        "quick_reply_label": "Removable Smart Save Stickers (Kiss-cut Mini Pages)",
    },
    {
        "productId": 73,
        "name": "Removable Smart Save Kiss-Cut Singles",
        "format": "Kiss-cut Singles",
        "material": "Removable Smart Save",
        "quick_reply_label": "Removable Smart Save Kiss-Cut Singles (Kiss-cut singles)",
    },
    {
        "productId": 74,
        "name": "Permanent Glow In The Dark Glossy",
        "format": "Die-cut Singles",
        "material": "Permanent Glow In The Dark Glossy",
        "quick_reply_label": "Permanent Glow In The Dark Glossy (Die-cut Singles)",
    },
    {
        "productId": 75,
        "name": "Permanent Gold Foil Image Transfer",
        "format": "Image Transfers",
        "material": "Permanent Gold Image Transfer Glossy",
        "quick_reply_label": "Permanent Gold Foil Image Transfer (Glossy)",
    },
]
