# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sy-qa-aichatbot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://syqaaichatbotregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1166aeb7750442099415f08fc766d5a2 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2cf6ec4631e545aa889de98750bd82ee }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: syqaaichatbotregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1166aeb7750442099415f08fc766d5a2 }}/autogen-chatbot:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sy-qa-aichatbot'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_967e7a0b04304d3d9137b6af000879c7 }}
        images: 'syqaaichatbotregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1166aeb7750442099415f08fc766d5a2 }}/autogen-chatbot:${{ github.sha }}'